@startuml

!theme vibrant
left to right direction
title Actores
Administrador as Admin
Cliente as Client
Tiempo as Time

package Aparcamiento{
    usecase "Dar de alta" as UC1
    usecase "Dar de baja" as UC2
    usecase "Verificar disponibilidad de plazas" as UC3
    usecase "Categorizar clientes" as UC4
    usecase "Edición de registro" as UC5
    usecase "Mostrar un listado" as UC7
    usecase "Eliminación de registro" as UC8
    usecase "Paginación del listado" as UC9
    usecase "Búsqueda de registro" as UC10
    usecase "Generación de documento Excel" as UC11
}

Admin --> UC1
Admin --> UC2
Admin --> UC5
Admin --> UC7
Admin --> UC8
Admin --> UC10
Admin --> UC11

UC1 -- UC3
UC7 -- UC4
UC7 -- UC9
UC5 .. UC3

UC1 -- Client
UC3 -- Time