@startuml

entity abono_tipos{
  *id <<PK>>
  --
  *nombre
  *monto
}

entity gym{
  *id <<PK>>
  --
  *cliente_id <<FK>>
  *payment_id <<FK>>
  *abono_tipo_id <<FK>>
  *modalidad_pago
  *fecha_alta
  fecha_baja
  *huella_activada
}

entity cuentas {
 *id <<PK>>
 --
 *titular
 *numero
 *tipo
 *documento_identidad
 *direccion
}

entity clientes {
  *id <<PK>>
  --
  *nombre
  *apellidos
  *documento_identidad
  *sexo
  fecha_nacimiento
  telefono
  email
  pais_nacimiento <<FK>>
  nacionalidad <<FK>>
  idioma <<FK>>
  titulation <<FK>>
  comentarios
  *interno
  *categoria
}


cuentas ||--|{ gym
clientes ||--|{ gym
abono_tipos ||--|| gym

@enduml