@startuml
!theme vibrant
left to right direction
title Actores
Administrador as Admin
Cliente as Client

package Gimnasio {
 usecase "Da de alta" as UC1
 usecase "Categorizar" as UC2
 usecase "Dar de baja" as UC3
 usecase "Generación de contrato" as UC4
 usecase "Edición de registro" as UC5
 usecase "Registro de huella" as UC6
 usecase "Mostrar un listado" as UC7
 usecase "Eliminación de registro" as UC8
}

Admin --> UC1
Admin --> UC3
Admin --> UC4
Admin --> UC5
Admin --> UC7
Admin --> UC8

UC1 -- UC6
UC1 --> Client

UC7 -- UC2

@enduml