@startuml

class Gym
class Cliente
class Pago
class Instalacion
class Maquina
class Ejercicio 

Cliente --* Pago : "ejecuta"
Pago --* Gym : "da acceso"
Gym --* Instalacion : "se compone"


Instalacion --o Ejercicio : "se lleva a cabo"
Instalacion --o Maquina : "tiene"
Maquina --o Ejercicio : "se lleva a cabo"

@enduml