@startuml

title Dar de alta a un cliente en el aparcamiento

start
:"Verificar si el residente existe";

if ("¿Está registrado el residente?") then (true)
    :Ingreso de datos de residente automático;
else (false)
    :Dar de alta con datos mínimos al cliente;
endif
: Ingreso de datos del pagador;
: Ingreso de tipo de abono;
: Ingreso de plaza de parking;
stop