@startuml

!theme vibrant
scale 50
title Edición de registro

start

: Actualización de datos (si se han modificado), 
 excepto los del cliente;

if(Cambia de plaza) then (true)
    : Verificacion de disponibilidad de plaza;
    if (Plaza disponible) then (true)
        :Crear registro de cliente;
        end
    else (false)
        :Denegar creación;
    end
    endif
else (false)
end
@enduml