@startuml

class Cliente
class Pago
class Aparcamiento

Cliente --* Pago : ejerce pago
Pago --* Aparcamiento : da acceso
Aparcamiento --* Instalacion : se compone de
Instalacion --o Vehículo : alberga

@enduml